// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyx1TrK2rioGmjPkW3mjkSp99paTqRjzw',
    appId: '1:629134466330:web:530a59e52c5a6f2b0c60a3',
    messagingSenderId: '629134466330',
    projectId: 'coookboookapp',
    authDomain: 'coookboookapp.firebaseapp.com',
    storageBucket: 'coookboookapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB9vz7nESPLooDlyfRjm8Ow76vZTCFoqI',
    appId: '1:629134466330:android:e0fd87d5956ab8380c60a3',
    messagingSenderId: '629134466330',
    projectId: 'coookboookapp',
    storageBucket: 'coookboookapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-HxpmWVkYAO0ZDczy5UTEIffRKDUjeU',
    appId: '1:629134466330:ios:5f4882340383ee750c60a3',
    messagingSenderId: '629134466330',
    projectId: 'coookboookapp',
    storageBucket: 'coookboookapp.appspot.com',
    iosClientId: '629134466330-2vodcb0f2qc755grncnj5noaf1asjibh.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookbookApp',
  );
}
